# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EarthNet2021
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  EarthNet2021 is a groundbreaking challenge and dataset to 
  advance the state of localized climate impact forecasting 
  using novel artificial intelligence methods.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.earthnet.tech" # the base hostname & protocol for your site
github_username:  earthnet2021

# Build settings
markdown: kramdown

remote_theme: "mmistakes/minimal-mistakes@4.21.0"

plugins: 
  - jekyll-include-cache